- Dockerfile
- Jenkinsfile
- package.json
Creates the CI needed.
Is based on an assumption that the build can be:
```
npm install
jekyll build
```
This also changes the npm dependency from being file-based to based on the [formation npm lib](https://www.npmjs.com/package/@department-of-veterans-affairs/formation)
> CI for vdsd

- Jenkinsfile
The vets team follows a convention as part of it's build-release-deploy (BRD) infrastructure whereby artifacts uploaded to S3 have one of the following names:
- `production.tar.bz2`
- `staging.tar.bz2`
- `development.tar.bz2`
For now, I'm trying to get `production` BRD complete front to back. `staging` & `development` will come later.
> Conform to BRD standard filenames

- Jenkinsfile
This PR:
1. Will only tar up the  contents of the `_site/` instead of the `_site/` dir itself. This way, when it gets uploaded + unzipped to the S3 bucket where it will be hosted, it will have the proper dir structure instead of having a root `_site/` directory.
2. Use the "dev-appropriate" filename as per the vagov build-release-deploy framework.
> Jenkinsfile tweaks for tar & upload filename

- _config.yml
- _config_gh_pages.yml
- deploy_site.sh
Deploying the current build 'as-is', to vets S3 bucket looks like this:
The path for the assets is rooted in `/vets-design-system-documentation`.
Work Done in This PR:
- change the `_config.yml` to have an empty `baseurl`
- create a separate `_config_gh_pages.yml` config that still has a `baseurl`:`/vets-design-system-documentation`
- updates the `deploy_site.sh` script to build with the new `_config_gh_pages.yml`
> change build path for gh_pages vs vets

- src/_includes/_mobile-nav.html
due to the change in the accordion, the component needed to have a stricter parent/child element relationship.
> fix mobile nav for change in accordion script

- package-lock.json
- package.json
- src/_components/alertboxes.md
- src/_components/html/alert-full-width.html
- src/_components/html/alert-full-width2.html
The full-width alerts are now in Formation. Here's some documentation for them. 
One thing I want us to do is to stop calling these "banners," so I am not going to reference them as such. They are a variant on the alert component, so we should call them full-width alerts, as the code implies, but I'm open to "page-width alerts" too, as long as we call it some kind of alert - though I think we should name them as we do in the code so we all use the same language.  
Please review the usage in the screenshot or page. I think I referenced everything in the github issue.
> full width alert documentation

- src/_content-style-guide/page-titles-and-section-titles.md
@DanielleSoCompany @bethpotts CC @RLHecht  - I’m unhiding the style guide topic for “Page titles and section titles” in the content style guide site. Please take a look at this PR page and let me know if you see any issues. 
Right now, we don’t have any character count limit per se for page titles and section titles ( H1s and h2, h3 headers). We do have  a count for the whole meta browser title in the SEO meta guidelines however. 
@DanielleSoCompany  - If we work backward from the SEO guidelines, it would mean that the character limit for H1 page titles are 41 with spaces (because 60 is the max with | Veterans Affairs).  
I was looking around our pages and some of the page title H1s are more like 50-60 characters long.  
I don’t see a big problem with that length - 60 characters for page …
> DRAFT page titles

- src/_components/html/sidenav-iframe.html
- src/_components/html/sidenav.html
- src/_components/promo-banners.md
- src/_components/sidenav.md
- src/_includes/iframe-preview.html
- src/_layout/flexbox-grid.md
- src/_layout/html/flexbox-grid-responsive-iframe.html
- src/_layout/page-templates.md
- src/_utilities/font-size.md
- src/_utilities/html/font-size-responsive-iframe.html
- src/_utilities/html/text-align-iframe.html
- src/_utilities/html/visibility-iframe.html
- src/_utilities/text-align.md
- src/_utilities/visibility.md
- src/assets/stylesheets/_components/_iframe-preview.scss
In some examples, the front matter is included in the snippet, along with other presentational markup required to improve the display of the example.
There is already a way to handle this, using a separate file for the snippet and the preview. This PR places that fix in all places. 
Another feature this PR adds is a link to view responsive previews in a new browser tab. 
This addition will help users see the example in a way they can adjust the viewport size with more flexibility, and preview the HTML from the snippet without digging through the iframe in the dev tools.
> improve snippets, open examples in new tab

- src/_content-style-guide/00_word-list.md
Added an entry for "benefit office" to explain this is not the correct term to use. Pointed users to VA regional office instead.
> Added benefit office entry.

- src/_components/alertboxes.md
The HTML snippets for the full width warning and full width informational alerts were swapped, so I swapped them back.
> Fix snippet error

- src/_content-style-guide/00_word-list.md
Change spelling of acronyms for Montgomery GI Bill Active Duty and Selected Reserve to MGIB-AD and MGIB-SR per education stakeholders.
> Fixing spelling of MGIB-AD and MGIB-SR

- src/_content-style-guide/dates-and-numbers.md
@DanielleThierryUSDSVA or @bethpotts  Could you please review this PR and merge? We had commas after the state abbreviations in the Like this Not this boxes, which shouldn't be there.
> Remove comma after state names

- src/_patterns/benefit-applications.md
I noticed a typo in this pattern in the design system docs:
> Fix typo in benefit-applications.md

- .circleci/config.yml
- Jenkinsfile
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/15169
in order to keep the deploy from overwriting the storybook deploy that is happening from the `veteran-facing-services-tools` repo, we need to do this in Circle rather than Jenkins.
Once this is merged, I will delete the following YAML configs from the devops repo:
- `deploys/vets-design-system-documentation-vagov-dev.yml`
- `deploys/vets-design-system-documentation-vagov-staging.yml`
We will only deploy to dev and staging when a new commit gets merged into master:
> Circleci deploy

- .circleci/config.yml
This fixes a recently noticed problem where we had `*.html` files from recent deploys, but older extensionless html files that were taking precedence in the browser.
Context: https://dsva.slack.com/archives/G01BJ3ESXL4/p1610037389032700?thread_ts=1610037383.032600&cid=G01BJ3ESXL4
Our solution is modeled after: https://simpleit.rocks/ruby/jekyll/tutorials/having-pretty-urls-in-a-jekyll-website-hosted-in-amazon-s3/
> Deploy fix

- src/_components/index.md
Reverts department-of-veterans-affairs/vets-design-system-documentation#354
This triggered a deploy which accidentally removed the thing we were linking to. Removing the link so we have more time to troubleshoot.
> Revert "Add storybook link"

- .circleci/config.yml
A [recent change to the deploy pipeline](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/369) introduced a bug which accidentally deleted the `/storybook` directory. This fixes it to prevent that from happening.
> Make sure storybook doesn't get deleted

- src/_data/display.yml
- src/_includes/header.html
- src/index.html
@mchelen-gov noticed a bug where a link was hardcoded to a page with an `html` extension, but the S3 bucket only has html files without an extension. This fixes that issue, but there are lots of other examples of this same thing happening.
Double checked that the links worked locally
After these changes, these are the only things that match my regex, and I _think_ they're ok:
[Slack thread for additional context](https://dsva.slack.com/archives/CBU0KDSB1/p1611250163022100)
> Remove hardcoded HTML extension from links

- src/_content-style-guide/dates-and-numbers.md
Taking March out of abbreviation list so we adhere to AP style
> Removing march from abbreviation list

- src/_patterns/form-templates.md
* URL was pointing to `#direct-deposit` but the actual URL should be `#direct-deposit-form`
---
> Updating the direct deposit anchor URL

- src/_content-style-guide/dates-and-numbers.md
Our style is to use only ET with hours. This needs to be added to the rules about phone numbers and the examples need to be updated. We also need to add directions about always including hours and days of operation when listing a phone number.
> Updating time zone info

- .circleci/config.yml
- _config.yml
- jekyll-configs/dev.yml
- jekyll-configs/prod.yml
- jekyll-configs/staging.yml
- src/_components/action-links.md
- src/_components/back-to-top.md
- src/_components/breadcrumbs.md
- src/_includes/storybook-preview.html
Like it says on the tin, this PR is a proof-of-concept for using iframes pointing to Storybook stories. They'll look like this:
Usage is pretty straightforward:
```
{% include storybook-preview.html story="components-back-to-top--default" %}
```
We can even include an optional `height` parameter in the `include` statement if desired.
> Using iframes to Storybook for component documentation

- src/_experimental-design/index.md
- src/_includes/_mobile-nav.html
Shawna [discovered a bug](https://dsva.slack.com/archives/C01Q9PDPLE9/p1619144454045100) in the mobile nav for the experimental design section. There was some copy pasta that needed to be re-jiggered.
> Fix the mobile nav for experimental design

- src/_design/image-aspect-ratios.md
> Fixing 3:2 image example (was showing 1:1 example)

- src/_includes/edit-on-github.html
Like it says on the tin, this is an attempt to be clearer about who can edit.
> Add (Permission required) to edit link

- src/_includes/edit-on-github.html
Per @rtwell's decision, this PR removes the edit link from the pages in the content style guide section of design.va.gov, but keeps it on the other pages.
Link removed from the content style guide pages:
Link kept for other pages:
> Remove the edit link from the content style guide pages

- src/assets/stylesheets/_components/_showcase.scss
Why were they even there in the first place? :confused:
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/267
**Note:** This doesn't update the actual headers on design.va.gov. They're still using Source Sans Pro. I don't know what the history of that is. :man_shrugging: 
**Note:** The H6 is still using Source Sans Pro, but that's how it is on va.gov as well. :man_shrugging:
> Remove the header font family override

- src/_includes/_mobile-nav.html
- src/_includes/_side-nav.html
With this change, we can add an `order` property to a page's front matter to change the order of that page in the side nav and the mobile nav menus.
> Sort the side nav based on order

- src/_documentation/for-developers.md
As of wc-v0.7.1, this is no longer needed.
> Remove postinstall docs

- src/_experimental-design/expandable-alert.md
Removing the link to the debt team's alert code since the alert is being removed from the application
> Remove debt team's alert code

- Gemfile
- Gemfile.lock
- _config.yml
- src/_includes/edit-on-github.html
- src/_includes/timestamps.html
- src/_layouts/default.html
- src/assets/stylesheets/_layout/_site-content.scss
Optionally adds timestamps to the bottom of the page. They only appear if the `date_added` or `last_updated` frontmatter appear on the page. This is intended for use in the experimental design section to keep track of when an experiment was added.
Ideally, these timestamps are updated automatically, but that was more work to figure out. :man_shrugging: This is the quick and dirty way to get _some_ information out there.
> Add timestamps

- src/_components/on-this-page-jump-links.md
Be more specific about when the component should be used. This is after a discussion with @rtwell and @cvalarida 
The goal here is to avoid incidents where "On this page" is used on pages which don't have `<h2>` elements, leading to unexpected behavior.
> Clarify "On this page" usage

- src/_patterns/form-feedback.md
- src/_patterns/html/error-checkbox.html
This PR moves the error message for the `<Checkbox/>` component in `src/_patterns/html/error-checkbox.html` to be located above the checkbox input rather than below it. Refer to this issue for details https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/535
> 29551: Update error message placement for <Checkbox /> component

- src/_content-style-guide/00_word-list.md
- src/_content-style-guide/punctuation.md
We need to add an entry about always using curly quote marks on VA.gov instead of the straight up and down ones.
> Adding quotation mark entry

- src/_components/loading-indicators.md
Point the loading indicator documentation to the story for the newly released Web Component
> Use correct loading indicator story

- src/_content-style-guide/bold-text.md
We needed to add a new bullet bout not using bold when it's better to have an H3 or H4 because the label is acting as a subhead.
> Adding when not to bold bullet 

- src/_documentation/for-developers.md
Part of https://github.com/department-of-veterans-affairs/component-library/pull/270
N/A
> Add web component custom events documentation

- src/_components/buttons.md
- src/_components/omb-info.md
[Ticket #35397](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/35397)
New page omb-info.md file was added.  This file contains all that is needed for the Jekyll build process to generate the HTML page with the examples on it, as well as add the necessary items to the left hand navigation.  
Still working on the Accessibility section.  There is just placeholder text in that section currently.
> CHORE: added new omb info page in docs

- src/_components/telephone.md
There was a missing comma in a telephone Storybook link that was causing tests to fail.
> fix: add missing comma to storybook link

- src/_components/additional-info.md
https://37935-remove-react-components-sb--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/37935
https://github.com/department-of-veterans-affairs/component-library/pull/339
> 37935 Remove React Components from Storybook

- src/_components/tables.md
The design.va.gov portion of https://github.com/department-of-veterans-affairs/component-library/pull/348. Add a warning about sort functionality for `<va-table>` in IE11
> Add warning about column sort in IE11

- package-lock.json
- package.json
https://github.com/department-of-veterans-affairs/va.gov-team/issues/38356
Tested locally and everything worked screenshots attached. Leveraged https://github.com/rogeriochaves/npm-force-resolutions per https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions since npm doesn't have resolutions and we are using an older version of NPM that didn't support overrides. Main issue is we are using gulp and their last release was 3 years ago and these are dependencies of that package.
> 38356 Dependabot Alert Fixes

- src/_components/modal.md
- src/_includes/storybook-preview.html
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/39968
> Update Modal link and link text to Storybook

- src/_components/form-controls.md
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/39964
> Update storybook link and text for Radio buttons

- .circleci/config.yml
- src/_about/maturity-scale.md
- src/_components/tabs.md
- src/_includes/_status.html
- src/assets/stylesheets/_components/_status.scss
Removes the comments that didn't prevent the push to production (though that is in progress). 
Fixes the link from component maturity scale tag to the maturity scale doc. 
Removes comment about Tabs that conflicts with maturity scale.
> Bug fixes to maturity scale addition

- .github/CODEOWNERS
Adding the platform design system team as a codeowner for all files in this repo.
> add design system team as codeowners

- src/_patterns/wizards.md
Link had pointed to `localhost`. Fixed to use `design.va.gov`. 
Additional Note: Maybe all link URLs should be updated to use `site.baseurl` across the entire page, instead of the hardcoded `design.va.gov` urls.
> Fix broken link

- src/_content-style-guide/page-titles-and-section-titles.md
@bethpottsVADEPO asked Sitewide Content to replace the Yoast.com link on the [Page titles and section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles) page with this: https://www.w3.org/WAI/tutorials/page-structure/headings/
I update the text to match our current link style.
> Changing link on page and section title page

- src/_data/component-docs.json
- src/_includes/component-docs.html
Updates the component-docs logic so that when a component does not have any props or events, the code usage section is not added to the page.
> update component-docs logic

- src/_components/breadcrumbs.md
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/35806
> Update link text and remove mobile story for Breadcrumbs

- src/_components/form/index.md
- src/_components/form/number-input.md
- src/_components/form/text-inputs.md
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39738
https://github.com/department-of-veterans-affairs/component-library/pull/395
> 39738 Number Input Documentation

- src/_includes/_site-in-this-section.html
This PR removes the extra slash in URLs in `In This Section`.
> chore: fix links for In This Section

- src/_components/alert.md
- src/_components/banner.md
- src/_includes/storybook-preview.html
We might be able to set the iframe height dynamically to fit its contents, but I haven't been able to test it locally because of cross-origin errors (Storybook runs on a different port locally). I think this would be considered "same-origin" on production? @bkjohnson @pdavies88 @k80bowman 
```diff
diff --git a/src/_includes/storybook-preview.html b/src/_includes/storybook-preview.html
index 1d19f9a..e862345 100644
--- a/src/_includes/storybook-preview.html
+++ b/src/_includes/storybook-preview.html
@@ -3,10 +3,18 @@
style="max-width: {{ include.width | default: '100%' }}"
>
<iframe
+    id="{{ include.story }}"
width="100%"
height="{{ include.height }}"
src="{{ site.storybook_path }}/iframe.html?id={{ include.story }}&viewMode=story"
></iframe>
</div>
+<script>
+  window["{{ include.story …
```
> Fit content inside iframe

- .github/workflows/issue-automation.yml
This should add any new issue that gets made in this repo to the GitHub project board that I'm using to explore some features.
The work is based on:
- [this discussion comment](https://github.com/github/feedback/discussions/5378#discussioncomment-2137318)
- [documentation on project automation](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects#example-workflow-authenticating-with-a-personal-access-token)
I'm merging this so that I can test some changes. This workflow is meant to trigger on `issue` events, and [the documentation on workflow triggers](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues) says:
> **Note**: This event will only trigger a workflow run if the workflow file is on the default branch.
> Add issues to board

- config/gulp/css.js
- config/gulp/javascript.js
- src/_components/form/index.md
- src/_includes/head.html
- src/_patterns/forms/index.md
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/710
This makes it possible for our web components to be used on design.va.gov. As an example I went ahead and updated the featured content components on the `components/form` and `patterns/forms` pages to use their web component versions.
> Setup web components for use on design.va.gov

- src/_about/maturity-scale.md
- src/_components/link/index.md
- src/_data/maturity-scale.yml
- src/_includes/_side-nav.html
- src/_includes/_site-side-nav-status.html
- src/assets/stylesheets/_components/_sidenav.scss
- src/assets/stylesheets/_components/_status.scss
Changes the shapes of some of the maturity icons. Carries those new shapes into the maturity level pages. Fixes a minor incorrect reference on the link page (could not help myself). [Fixes #777]
> Changes the source order of the maturity icons. 

- src/_components/banner.md
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/40187
https://github.com/department-of-veterans-affairs/component-library/pull/430
> 40187 Banner Documentation Update

- src/_components/alert.md
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/791
https://github.com/department-of-veterans-affairs/component-library/pull/431
> 791 Dismissable Background Example

- src/_components/form/index.md
- src/_components/form/text-input.md
- src/_components/form/text-inputs.md
- src/_components/form/textarea.md
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/40157
[Related PR](https://github.com/department-of-veterans-affairs/component-library/pull/432)
This PR splits Textarea into its own subpage under Forms. 
Other text inputs page changes were done to use the singular noun now that textarea has its own page.
> Update Textarea documentation

- src/_content-style-guide/dates-and-numbers.md
- src/_content-style-guide/html/telephone.html
Reverts department-of-veterans-affairs/vets-design-system-documentation#893
Reverting for now since the `<va-telephone>` web component is not available for use inside Drupal yet ([see Slack convo here](https://dsva.slack.com/archives/C01DBGX4P45/p1653316713861639))
I have reached out to the CMS team to see about adding the `<va-telephone>` web component to the list of elements allowed in Drupal. There is a ticket for that work, but it may be a couple of months before they can complete it ([see Slack convo here](https://dsva.slack.com/archives/CT4GZBM8F/p1653319471617409)).
> Revert "Recommend telephone web component"

- .github/workflows/deploy.yml
We noticed recently that the "Last updated" text near the bottom of pages shows the date of the last deploy:
This defect was introduced with https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/793. By changing the checkout action to [include the full git history](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches) we get the expected date:
This matches the repo history:
> Fix "Last updated" date

- .github/ISSUE_TEMPLATE/component_development.md
This PR updates the component development template to include steps for updating design.va.gov with the latest version of component-library to have the latest component-docs.json. We use the component-docs.json to generate the `Code Usage` section for our web components.
> Update component development template

- package-lock.json
- package.json
- src/_components/telephone.md
I opened #1072 while I was trying to work on this. This is a followup to https://github.com/department-of-veterans-affairs/component-library/pull/492#pullrequestreview-1051350575
> Add tty telephone example

- src/_components/alert-expandable.md
We would like to encourage teams to only use the info and warning variations of the expandable alert, at least for now. This PR just comments out the other variations for now. We can uncomment or delete them later based on future discussions.
> hide invalid expandable alert types

- .github/ISSUE_TEMPLATE/DST-component_design.md
Adds a small update to the component design ticket template for conducting a small audit when we are building a new version of a pre-existing component.
> add small audit to design ticket

- .github/ISSUE_TEMPLATE/DST-component_development.md
- .github/ISSUE_TEMPLATE/DST-component_final_review.md
- add details about What's New Confluence page to Final Review issue template
- add task and AC for analytics to Development issue template
> Update Final Review and Development issue templates

- src/_components/omb-info.md
Part of #985 
This PR updates the Storybook examples and adds an `Open Issues` link to OMB info.
> Update Storybook for OMB info

- .github/ISSUE_TEMPLATE/1_bug_template.md
- .github/ISSUE_TEMPLATE/DST-component_development.md
Adds questions about urgency to the bug issue template. Also adds the dst-engineering label to the component development issue template.
> Add urgency details to the bug template

- src/_components/form/date-input.md
- src/_components/form/memorable-date.md
- src/_components/form/radio-button.md
- src/_components/link/index.md
- src/_includes/_side-nav.html
- src/_includes/_site-side-nav-status.html
I wanted to share this to show my work and to demonstrate how using the component-docs.json file is just not going to work for a number of reasons. Thus I'm going to have to refactor this to use the front matter in Jekyll instead. Here are the problems:
1. Maturity naming. We took some liberties in the naming of the maturityCateogry and maturityLevel. For example, "caution" instead of "use-with-caution" and "best_practice" instead of "best-practice". This isn't so hard to overcome and I did so in this code but, it's annoying.
2. Component naming. We also are inconsistent here and thus trying to take the title of the page and using slugify and append to come up with the component name is not working for some components. 
* Sometimes it is just an abbreviation of the full title: "Radio …
> Fixes maturity level indicator in sidenav for sub-pages. [Amends #1255]

- package-lock.json
- package.json
Related to https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1298
Now that we have published a version of the `component-library` with the doc changes, we can update the documentation site to be consistent with storybook:
This is to get an updated prop description for the telephone component's contact prop. The change was made available in [version `13.3.0`](https://github.com/department-of-veterans-affairs/component-library/releases/tag/v13.3.0)
> Bump component-library to 13.4.0

- package-lock.json
- package.json
With the addition of the v3 variation to [va-radio](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--default) and [va-text-input](https://design.va.gov/storybook/?path=/docs/uswds-va-text-input--default) as well as [`hint` prop](https://github.com/department-of-veterans-affairs/component-library/pull/592) added to multiple form components, this will update the documentation site to be consistent with Storybook.
https://github.com/department-of-veterans-affairs/component-library/releases/tag/v13.6.0
> Bump component-library to 13.6.0

- package-lock.json
- package.json
Latest version release notes: https://github.com/department-of-veterans-affairs/component-library/releases/tag/v13.9.0
Verified that this repo ran locally with the packages updated:
> Update component-library to latest version 13.9.0

- src/_about/developers/using-web-components.md
This adds the `va-omb-info` and `va-file-input` components to the list and also adds more clarity around the types of migration options available.
There is more detail about why I've updated the description for some of these migration types in the ticket comment here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1692#issuecomment-1535074604
> Update web component migration docs

- src/_about/developers/using-web-components.md
This PR:
- removes any web components that don't directly map to a deprecated React component, and 
- removes any web components that has already had all of their React counterparts removed, and
- updates the remaining web component migration type for their corresponding React component
Quick explanation of the migration types:
**Manual Migration** - No auto-migration exists but there is an ESLint error/warning in code editors. Links to Storybook.
**ESLint Rule** -  Auto-migration exists via ESLint and there is an ESLint error/warning in code editors. Links to rule.
**Migration Script** - An auto-migration exists through a custom migration script run in CLI. Links to script.
closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1703
> Update web component migrations list

- src/_components/card.md
- src/_patterns/help-users-to/complete-a-sub-task.md
There were a couple of links that were causing a 403 error page to display. Removing the trailing backslash seems to fix it:
> Remove trailing slash from links that cause a 403 forbidden errors

- src/_about/developers/using-web-components.md
These updates are for the `/about/developers/using-web-components` page to add a little more detail and context to help teams migrate their design system React components to Web Components. For example, how to implement either the react binding or the vanilla component:
Related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1608
> Update web component usage docs

- src/_about/developers/contributing.md
- Fixed a couple broken links and an incorrect anchor at the top of the page
- Added a "front-matter" definition section
- Added a "time to prod" timeline section
Closes #1717
> Fixes and additions to developer contributing docs

- src/_about/developers/using-web-components.md
The React Table component has been deprecated and removed so I am removing it from the [migration list](https://design.va.gov/about/developers/using-web-components#web-component-migrations).
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1658
> Remove table from web component migration list

- src/_includes/content/form-labels-masterlist.md
This is an attempt to temporarily fix the issue of `va-accordion` not displaying on the [form labels list page](https://design.va.gov/content-style-guide/form-labels#form-label-masterlist).
Previewed locally:
> Manually add hydration class to web component for the form labels list

- src/_about/developers/using-web-components.md
Since the Telephone React component has been deprecated and all instances replaced with va-telephone, we can remove it from the [web component migrations list](https://design.va.gov/about/developers/using-web-components#web-component-migrations).
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1631
> Remove va-telephone from the React migration list

- src/_about/developers/using-web-components.md
The React `Checkbox` component has been replaced with the `va-checkbox` and deprecated so this PR removes it from this migration list:
related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1920
> Remove va-checkbox from migration list

- README.md
I noticed that the README of this repo does not mention the component-library (only Formation) and it did not link to it. Also made some minor grammar/wording updates to that paragraph.
> Add component-library link to readme and adjust wording

- config/gulp/build.js
- config/gulp/storybook.js
- gulpfile.js
This PR introduces a new Gulp task that automates the process of copying assets from the `storybook/assets/ `directory to the root `assets/` directory. This ensures consistent asset paths across different environments, addressing the issue of assets not being found in the production environment.
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1977
>  Copy Storybook Assets to Root Directory using Gulp

- src/_about/developers/using-web-components.md
This PR removes the `va-breadcrumbs` from the migration list as it has been replaced with the web component.
closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1632
> remove va-breadcrumb from migration list

- src/_components/modal.md
The va-crisis-line-modal component Storybook story was not displaying in the iframe because it was pointing to the incorrect Storybook link.
> Update va-crisis-line-modal Storybook link

- src/_patterns/ask-users-for/multiple-responses.md
there's no "examples" section in the page anymore, so the "examples" anchor link is broken https://dsva.slack.com/archives/C0NGDDXME/p1705943992084859?thread_ts=1705940075.543229&cid=C0NGDDXME
> Removing unused "examples" anchor on Multiple Responses pattern

- src/_about/developers/contributing.md
This PR will update the developer contribution docs to make it clearer how teams can contribute back to the design system component library.
The page can be reviewed locally at: http://127.0.0.1:4000/about/developers/contributing
closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2446
> Update developer contribution documentation

- src/_components/form/checkbox.md
- src/_components/form/radio-button.md
- src/_includes/content/conditionally-revealed-fields.md
- src/_patterns/ask-users-for/a-single-response.md
- src/_patterns/ask-users-for/relationship.md
Currently, guidance for conditionally revealed fields is buried in the "Relationship to the Veteran" Pattern. This PR turns that guidance into a partial, so it can be included on
- Ask users for a single response (one thing per page)
- Radio Group
- Checkbox Group
When the forms team has a content-agnostic version of this pattern available in the forms library, I will update the guidance with links to that code.
> Unbury Conditionally Revealed guidance

- src/_about/experience-standards.md
Headings for standards under Efficiency were at H3, should be H4.
> Fix heading levels for Efficiency experience standards

- src/_about/developers/using-web-components.md
We are holding off on the auto-migration script for now until we are ready to set the linting rule to an error. Otherwise, this script was running without teams awareness and causing some issues in PRs. Commenting out the migration script section from the docs for now and we'll add it back when the migration script is active.
https://design.va.gov/about/developers/using-web-components#how-to-migrate-from-font-awesome-to-va-icon
> Comment out va-icon auto migration section

- src/_about/accessibility/index.md
replaced links at the bottom of the page with links to sections on the newly launched accessibility landing page on Platform. (this page launched before that one, so the links that were originally included were placeholders.)
> Update index.md with updated links

- package.json
- src/assets/stylesheets/_components/_badge.scss
- src/assets/stylesheets/_components/_component-checklist.scss
- src/assets/stylesheets/_components/_contributors.scss
- src/assets/stylesheets/_components/_do-dont.scss
- src/assets/stylesheets/_components/_example.scss
- src/assets/stylesheets/_components/_header.scss
- src/assets/stylesheets/_components/_hero.scss
- src/assets/stylesheets/_components/_iframe-preview.scss
- src/assets/stylesheets/_components/_in-this-section.scss
- src/assets/stylesheets/_components/_mobile-nav.scss
- src/assets/stylesheets/_components/_on-this-page.scss
- src/assets/stylesheets/_components/_resource-links.scss
- src/assets/stylesheets/_components/_search-results.scss
- src/assets/stylesheets/_components/_showcase.scss
- src/assets/stylesheets/_components/_sidenav.scss
- src/assets/stylesheets/_layout/_content-wrappers.scss
- src/assets/stylesheets/_layout/_site-content.scss
- src/assets/stylesheets/application.scss
- src/testing/doctors.html
- yarn.lock
This PR bumps the version of component-library to 42.1.0
**After updating formation and rem values**:
> bump component-library to 42.1.0

- src/_includes/footer.html
The search functionality isn't working and I believe it's because there's a rogue forward slash on the src path for the script that handles it so this PR will remove that.
> Remove forward slash from site.js src link

- src/_foundation/icons.html
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1616
Updated the icon guidance now that we have `va-icon`. This is simplified to say icons are decorative in their usage and should not be used on their own without a visible label.
> Update icon a11y guidance

- src/_components/divider.md
Linked to the wrong story, which is causing it not to display.
> Fix story link to display component in storybook properly

- src/_includes/a11y/alerts.md
Docs updates for https://github.com/department-of-veterans-affairs/component-library/pull/1221 to clarify how to use ARIA roles a bit more.
> Add more information and examples for va-alert roles

- src/_components/form/input-message.md
- src/_components/sidenav.md
- src/_patterns/help-users-to/check-eligibility.md
- src/_patterns/help-users-to/complete-a-sub-task.md
- src/_patterns/help-users-to/keep-a-record-of-submitted-information.md
- src/_patterns/help-users-to/navigate-a-long-list.md
I decided to remove the broken links to Sketch even though we do not have all templates in Figma just yet.
> Removes all sketch links. [Amends #2472]

- src/_content-style-guide/title-tags.md
Updated formatting on the examples in the [Exception 2: forms and subtasks title tags section](https://design.va.gov/content-style-guide/title-tags#exception-2--forms-and-subtasks) to be more clear. The current formatting doesn't exactly match the text in the word doc shared in #2415, which is resulting in incorrect guidance. I broke the examples out into a nested UL for easier understanding.
> Update formatting of title tags examples

- package.json
- src/_components/button/index.md
- src/assets/stylesheets/_components/_code-snippets.scss
- src/assets/stylesheets/_components/_footer.scss
- src/assets/stylesheets/_components/_header.scss
- src/assets/stylesheets/_components/_link.scss
- src/assets/stylesheets/_components/_search-results.scss
- src/assets/stylesheets/application.scss
- yarn.lock
updates component library and css library versions
> update component library and css library

- src/_includes/content/phone-numbers.md
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3040
This removal is based on the background outlined in this issue https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2884 and discussions with the a11y group at VA. We have removed the ARIA label from the telephone component itself, so this guidance should also be updated to remove that guidance for links, as spacing out the phone number in a label is no longer needed.
> Remove ARIA label guidance for phone numbers

- src/_content-style-guide/links.md
Adding the missing On this Page link for the new section on the [links page](https://design.va.gov/content-style-guide/links) "Linking to pages on VA.gov"
> Update links.md - add "on this page" link for new section

- src/_components/url-standards/redirects.md
per @mnorthuis, we are removing some language under the [redirect guidance](https://design.va.gov/components/url-standards/redirects) for "when not to use" - we want teams to ask us if they need a redirect before removing something permanently and causing a 404.
> Update redirects.md to remove "okay to serve up 404" language

- src/_components/url-standards/redirects.md
We had a bonus "On this page" section on the [URL Redirects page](https://design.va.gov/components/url-standards/redirects). Thanks @danbrady for the catch!
> Update redirects.md - Remove extraneous "On this page"

- src/_about/developers/using-web-components.md
This request is based off [this comment](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3228#discussion_r1735446202).
> Remove guidance on how to migrate to web components

- src/_components/url-standards/index.md
- src/_components/url-standards/redirects.md
- src/_components/url-standards/vanity-urls.md
Per @mnorthuis updates to VADS guidance for URL standards:
- Broke out Vanity URL guidance into its own child page of URL standards
- Added "sub-URL" guidance for form flows to URL standards main page
- Updated formatting on all three URL component pages (including redirects page)
- Updated link to submit GitHub issue on Vanity URLs and Redirects pages
https://github.com/department-of-veterans-affairs/va.gov-team/issues/88407 https://github.com/department-of-veterans-affairs/va.gov-team/issues/90080
> Update URL standards guidance for Vanity URLs and Form flow URLs

- src/_patterns/help-users-to/know-when-their-information-is-prefilled.md
**Description:**
Fixes some updates that came from tickets in the staging review.
Fixed 'Design Principals' 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3367
Replace 'however' with 'but'
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3370
Remove contextual alert content
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3371
fix "note" in content
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3373
split up run on sentence
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3376
add hyphens to wording
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/is …
> Updates from staging review tickets

- src/_components/form/prefill.md
- src/_patterns/help-users-to/know-how-their-information-is-updated.md
Summary:
CAIA recommended adding some alerts to the 2 pages that pertain to the prefill pattern.
Form - Prefill page:
Know how their information is updated - Pattern page:
Ticket this addresses: https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/168
> Prefill pattern - add alerts with links to the 2 pages related to prefill

- .github/workflows/pull-request.yml
This PR will remove the `development` and `staging` build checks from the pull-request workflow because they are either redundant or unnecessary. 
- The `development` environment build is already being tested by the [preview workflow](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/.github/workflows/preview.yml) (redundant)
- The `staging` environment is not currently being used in any meaningful way (unnecessary)
> Remove development and staging environments from build check

- _config.yml
- src/_about/developers/using-web-components.md
- src/_about/naming.md
- src/assets/javascripts/components/code-snippets.js
- src/assets/stylesheets/_components/_code-snippets.scss
- src/assets/stylesheets/_layout/_content-wrappers.scss
- Adds syntax highlighting to code blocks via [rouge gem](https://github.com/rouge-ruby/rouge)
- Adds a `copy` button to easily copy code to clipboard. This is not something we have to include, but I thought it was a nice addition. It uses the VA button and only about 35 lines of JS to get the copy functionality working.
- Syntax styling aka theme for code styling taken somewhat from some of the existing styles, but instead of using hardcoded color values was able to sass variables instead. I commented on what each class style is responsible for as far as syntax highlighting, but let me know if any of that looks incorrect or should be changed. The old styles weren't actually used at all since highlighting was not set up in the _config.yml.
I went through the site to look for any styling …
> Add syntax highlighting for markdown code blocks

- src/_components/form/progress-bar-segmented.md
The Accessibility considerations link on the progress indicator page was pointing to USWDS alert. This PR fixes the link
> Update link to USWDS from VADS progess indicator

- src/_about/developers/using-web-components.md
On the developers page for using web components, the Storybook link was pointing to the old version of the main storybook page.
- From this ❌ https://design.va.gov/storybook/?path=/docs/about-introduction--page
- To this ➡️ https://design.va.gov/storybook/?path=/docs/about-introduction--docs
> Fix storybook link

- package.json
- yarn.lock
Reverts department-of-veterans-affairs/vets-design-system-documentation#3763
Reverting because we're seeing some regressions with how source sans pro is being loaded.
> Revert "Update component library to v49.0.0"

- src/_components/table.md
Removes [this section](https://design.va.gov/components/table#examples---v1) since v1 code was removed:
> Remove v1 table docs section

- README.md
- _config.yml
These steps should get the components loading again locally. But....
⚠️  The component-library PR below needs to be merged first.
🛠️  After that's merged, pull down those component-library updates locally and run `yarn install` (just needs to be done once). Then the Storybook server should start using the steps this PR adds.
Related component-library pr:
- https://github.com/department-of-veterans-affairs/component-library/pull/1495
> Add Storybook local preview steps and update the localhost port number

- src/_components/alert/index.md
Removed the sign-in alert info from the main alert documentation page as their is a subcategory specifically for sign-in alerts that is more up-to-date. (per [#3783](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3783) )
> [PR] Updated the alert documentation per #3783 (Update index.md)

- README.md
> README.md: Add Updating What's New process 

- .github/prompts/Guidance-follow-content-style-guide.md
- .github/prompts/Guidance-follow-content-style-guide.prompt.md
- src/_components/link/index.md
- src/_foundation/typography.md
- src/_includes/content/avoid-links-in-headers.md
Adds a11y guidance in both Typography > Headers and Link that makes clear when it is and is not appropriate to use links in headers. Also, adds to the copilot prompt in VS Code for reviewing guidance using the content style guide.
Closes #[#2146](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2146)
[Open Preview Environment](https://dev-design.va.gov/4041)
> Headers: Adds a11y guidance on avoiding links in headers. [Fixes #2146]

- src/_components/form/checkbox.md
- src/_components/form/text-input.md
- src/_includes/content/conditionally-revealed-fields.md
- **Checkbox: Adds guidance on choosing between variations. [Fixes #2204]**
- **Some copilot directed content improvements to guidance.**
Closes [#2204](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2204)
[Open Preview Environment](https://dev-design.va.gov/4043)
> Checkbox: Adds guidance on choosing between variations.

- src/_components/breadcrumbs.md
- src/_includes/storybook-preview.html
Allows us to pass a scrollable param to the iframe of Storybook components, when necessary. This was the best copilot and I could come up with. What an irritating problem. Devs on the team should check the responsiveness of their examples in future.
Closes #[3276](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3276)
[Open Preview Environment](https://dev-design.va.gov/4048)
> Fixes scrolling in iFrames where we need horizontal scrolling. [Fixes #3276]

- src/_components/form/checkbox.md
Checkbox: Adds mobile examples.
Closes #[3829](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3829)
[Open Preview Environment](https://dev-design.va.gov/4079)
> Adds mobile examples to checkbox guidance. [Fixes #3829]

- src/_content-style-guide/health-content/destigmatizing-language-for-weight.md
Fixing the first link under Additional resources. It wasn't linking in the live page although the preview looked okay; this may have been because of the vertical bar in the title, which is now a comma.
> Destigmatizing language for weight: Fixing link

- src/_components/alert/index.md
- src/_components/banner/index.md
- src/_components/banner/maintenance.md
Adds a link to our downtime notification guidance in Alert, Banner, and Banner - Maintenance, which are all places a user may look to find application-level downtime guidance.
I did not create an issue for this but had it on a personal todo list for awhile (please excuse my bad behavior).
[Open Preview Environment](https://dev-design.va.gov/4254)
> Alert: Adds a link to our downtime notification guidance in a number of components

- package.json
- yarn.lock
This PR updates the version of component-library to latest, 51.1.0.
[Open Preview Environment](https://dev-design.va.gov/4370)
> bump version of component-library

- src/_components/alert/index.md
Adds clear guidance for link styling within alert components to resolve confusion from health teams about when to bold links in alerts. The new "Links within alerts" section provides specific guidance on action links vs standard links and clarifies that bold text should not be used for standard links.
Closes #4417
Preview will be available at: `https://dev-design.va.gov/[This_PR_number]` once automated checks complete.
Changes can be previewed at: `/components/alert/` in the "Links within alerts" section under "How to use alerts".
[Open Preview Environment](https://dev-design.va.gov/4421)
> Alert: Adds link styling guidance

- src/_components/link/action.md
Fix typo in Link - Action docs
N/A
[Open Preview Environment](https://dev-design.va.gov/4619)
> Fix typo in Link - Action docs

- src/_components/link/index.md
In the accessibility cop channel we discussed issues with va-link not enlarging in some instances for users.  
We were finally able to recreate the issue in this way:
- In browser settings, change the font size to very large (this does not work when just using traditional browser zoom with ctrl and plus)
See this [slack thread for more details](https://dsva.slack.com/archives/C01DBGX4P45/p1735058549203829)
We need to update guidance to let teams know they need to wrap `<va-link>` in a semantic tag like `<p>`. We can't bake it into the component at this point, because there are other semantic tags that also work like headings and lists. A `<div>` or `<span>` just won't work here.
N/A
[Open Preview Environment](https://dev-design.va.gov/4742)
> Adding accessibility guidance for va-link
