src/_content-style-guide/index.md

11/1/18
Welcome... content style guide --> "VA.gov content style guide"
Principles --> "Content principles"

Updating VA.gov content style guide landing page

---

src/_content-style-guide/sections/error-messages

Add "Error messages" as nav item in Content Style Guide section. JLee, 11/2

Adding section "Error messages" file

---

src/_content-style-guide/sections/buttons

Add "Buttons" file in Content Style Guide section. JLee, 11/2.

Add "Buttons" in Content Style Guide files

---

src/_content-style-guide/sections/va-forms.md

Added content to va-forms file. JLee, 11/2.

Updated va-forms > Content Style Guide

---

src/_content-style-guide/sections/word-list.md

Updated the word list. JLee, 11/2.

Updated word-list file > Content Style Guide

---

src/_content-style-guide/sections/web-policies-and-directives.md

"...directives" file in Content Style Guide section. JLee, 11/2.

Add placeholder text to "Web policies and..."

---

src/_content-style-guide/sections/ui-elements.md

Spell out UI - some of our VA users won't know what UI is.

Change UI Elements to "User interface elements"

---

src/_content-style-guide/sections/error-messages

Updated error-messages file on content style guide. JLee, 11/6.

Added placeholder text to error-messages file

---

src/_content-style-guide/sections/capitalization.md

Placeholder text for discussion. JLee 11/6.

Updated capitalization.md file

---

Jenkinsfile

We only want to archive & deploy builds from the `master` branch.

Only archive on master branch builds

---

src/_layouts/default.html
src/assets/stylesheets/_components/_header.scss
src/assets/stylesheets/_components/_hero.scss
src/assets/stylesheets/_components/_resource-links.scss
src/assets/stylesheets/_components/_sidenav.scss
src/assets/stylesheets/_helpers/_clip.scss
src/assets/stylesheets/_layout/_site-content.scss
src/assets/stylesheets/application.scss
src/index.html

This PR will update the design of the landing. It still needs images, but it's good enough to go forward.

everything but the images

---

src/_content-style-guide/we-us-you.md

@jaredcunha-usds - just checking if I used your table html snippet correctly. Does it look ok?

Adding we, us, you text

---

src/_content-style-guide/bulleted-lists.md
src/_content-style-guide/lists.md

@jaredcunha-usds -- Added contents and changed filename to "bulleted-lists" to reflect topic. Would like this to appear in the nav as Bulleted lists. Not sure if just changing the filename will do that. Can you check and deploy if no issues?

Update and rename lists.md to bulleted-lists.md

---

src/_content-style-guide/00_word-list.md

Hi @jenniferlee-dsva. I've addressed all of the questions, with the exception of a couple which I'm asking Beth and Randi to look at. Lots of edits as well as some notes and questions. Feel free to reach out with any questions. Thanks!

Danielle edits, response, additions

---

src/_content-style-guide/abbreviations-and-acronyms.md
src/_content-style-guide/naming.md
src/_content-style-guide/numbers.md
src/_content-style-guide/page-titles-and-section-titles.md
src/_content-style-guide/ui-elements.md
src/_content-style-guide/web-policies-and-directives.md
src/_includes/_mobile-nav.html
src/_includes/_side-nav.html

create draft capability

---

src/_content-style-guide/health-content.md

@jaredcunha-usds - I added this new MD. Could you make sure it looks okay? I used your Like this/Not this snippet, but hard to tell if the formatting looks okay without a real preview.

Update and rename health-content to health-content.md

---

src/_content-style-guide/dates-and-numbers.md

@jaredcunha-usds - I wanted to add Beth Potts and Randi Hecht as reviewers to this update, but they don't come up in Reviewers list of options. Can you add them or can I simply share the link with them to this branch? (Will they be able to see if they're not in the repo list of ppl?) 
Jen

Added new guidance: vanity ph#s

---

src/_components/alertboxes.md
src/_components/html/alert-background-color.html
src/_components/html/alert-continue.html
src/_components/html/alert-error.html
src/_components/html/alert-informational.html
src/_components/html/alert-success.html
src/_components/html/alert-warning.html

based on our conversation in the design, trying to clean up documentation on alert component, specific, the background-color-only modifier. 
For details, see this comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/52#issuecomment-487728461

WIP: changes to background-only alerts

---

src/_content-style-guide/bulleted-lists.md

Per list, not per page @RLHecht

WIP - update guidance bullet list

---

src/_content-style-guide/abbreviations-and-acronyms.md

OCC - Office of Corporate Comms ; Office of Community Care; Office of Connected Care
GSM - Grants Management Services
NO BAD Examples
@RLHecht

WIP - guidance internal office acronyms

---

src/_patterns/signed-out-signed-in.md

@smoonpeyes This is where I'm drafting your work to ready it for design.va.gov

WIP: signed out singed in page

---

src/_patterns/benefit-applications.md

This pull request puts together all of the benefit application content from @smoonpeyes @peggygannon and @KevinMHoffmanUSDS so we can evaluate the page as a whole and decide how we want to go about editing. I did not make any changes to the content except for linking links and standardizing the heading levels.
If you want to view this as a markdown page, you can go to the [edit view](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/edit/benefits-application-documentation/src/_patterns/benefit-applications.md?pr=%2Fdepartment-of-veterans-affairs%2Fvets-design-system-documentation%2Fpull%2F92) and click on the Preview tab. Just, don't push any updates you don't intend to.
Here's a screenshot:

WIP: benefit application page

---

src/_content-style-guide/zz-sign-up-for-updates.md

Renamed md file and added slug so that Sign up for updates goes to bottom of left nav.

Update and rename sign-up-for-updates.md to zz-sign-up-for-updates.md

---

src/_content-style-guide/00_word-list.md

Adding the appeals entries to word list as well as the terms Blue Water and Brown Water.

Appeals additions to Word List

---

src/_documentation/index.md
src/_patterns/benefit-applications.md

Content fixes from this issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/122

punctuation and minor content updates

---

src/_content-style-guide/00_word-list.md

Adding appeals entries to word list in style guide.

Adding appeals entries to word list

---

src/_content-style-guide/00_word-list.md

This is still a WIP but some entries have been added.

Adding Vets.gov word list entries to VA.gov style guide

---

src/_content-style-guide/00_word-list.md

Reverting my premature merge of #141

Revert "Adding Vets.gov word list entries to VA.gov style guide"

---

src/_documentation/whats-new.md

I added the entries to the What's new section for December updates.

Added December what's new info

---

src/_components/html/promo-banner-envelope-iframe.html
src/_components/html/promo-banner-envelope.html
src/_components/html/promo-banner-iframe.html
src/_components/html/promo-banner-newspaper-iframe.html
src/_components/html/promo-banner-newspaper.html
src/_components/html/promo-banner.html

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/4747
This PR updates the HTML docs for the promo banners to reflect the [updated <PromoBanner /> React markup](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/203).

Kelsonic 4747 update promobanner html docs

---

src/_content-style-guide/00_word-list.md

Apostrophe needed in word list entry for Board of Veterans' Appeals

Add apostrophe to Board of Veterans' Appeals

---

src/_content-style-guide/writing-for-seo.md

updated VAMC meta title exceptions. @RLHecht - if this looks good, lmk before you publish. I want Dave on the VAMC team to review prior to publishing.

updated VAMC meta title exceptions

---

src/_content-style-guide/abbreviations-and-acronyms.md
src/_content-style-guide/dates-and-numbers.md

Adding an entry in the dates, times, and phone numbers section of style guide to include guidance on street addresses.

Adding entry on street addresses

---

src/_content-style-guide/dates-and-numbers.md
src/_documentation/whats-new.md

Added list of style guide changes for April in the What's New section.

April What's New topics added

---

src/_content-style-guide/dates-and-numbers.md

changed wrong - hyphen to "to" in an example @RLHecht

changing wrong hyphen to "to" in example

---

src/_documentation/whats-new.md

@RLHecht -- I fixed a couple minor issues with formatting and style.

Fixed inconsistent formatting and punctuation

---

package-lock.json
package.json

This PR upgrades the Formation/Formation-React dependencies to align with vets-website, https://github.com/department-of-veterans-affairs/vets-website/blob/cd0117621dd89724e2c66a1cf4879f37c424b6df/package.json#L261

Bump Formation to 6.9.2

---

src/_content-style-guide/bold-text.md

Inputting Beth's draft of when and how to use bold text to new page in content style guide.

Adding bold text page to style guide

---

src/_content-style-guide/naming-and-labels.md

@bethpotts I've updated the example to change VR&E to VA.

Updating example in Naming and Labels section

---

src/_content-style-guide/dates-and-numbers.md

@DanielleThierryUSDSVA I updated this entry per our convo yesterday about keeping the +1 in the code if it's not causing any issues.

adding +1 inside aria label code for phone numbers

---

src/_content-style-guide/00_word-list.md

This was added to word list since different from AP Style guidance

Adding FAQs to Word List

---

package-lock.json

Got a new `package-lock.json` after deleting the old `package-lock.json` (also `node_modules`) and re-running `npm install`.

Regenerated package-lock.json.

---

src/_components/form-controls-date.md
src/_components/html/date.html

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/20614
Add a date snippet to the Date component documentation.

Add date snippet

---

src/_components/html/date.html

Don't abbreviate months

---

README.md
src/_design/html/links.html

closes https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/21571
Updates link section to look like this:

update link section and add ruby version to readme

---

_config.yml
src/_experimental-design/index.md
src/_includes/_mobile-nav.html
src/_layouts/default.html

Adds an Experimental Design section to the design system site.

add experimental design section

---

package-lock.json
package.json
src/_components/action-links.md

Updated the action links documentation to reflect the new class names. Also noticed that we were using an older version of Formation, so I updated that as well.

update formation version and action link class

---

README.md
package.json
webpack.config.js

While I was trying to run this locally, I found a few things to update. Nothing much.

Minor updates

---

jekyll-configs/prod.yml
src/_includes/head.html
src/_layouts/default.html

Adds analytics to the production build for design.va.gov.
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/23296

Add analytics

---

src/_includes/edit-on-github.html
src/_layouts/default.html

Adds a handy link to open a new tab to edit the file in GitHub.

Edit this page in GitHub link

---

src/_components/index.md

It's no longer a pilot. :man_shrugging:

Remove the blurb about the Storybook Pilot

---

src/_components/address-block.md

Requires https://github.com/department-of-veterans-affairs/component-library/pull/86
See the description of :point_up: for more information and screenshots.

Use the new address block story

---

src/_components/action-links.md

This requires an update to the component library to use `<Story>` in the MDX file. The PR for that can be found here: https://github.com/department-of-veterans-affairs/component-library/pull/85.

Split action links into multiple stories

---

src/_documentation/for-developers.md

Related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/23328
This updates the developer documentation

Update developer docs

---

src/_documentation/for-developers.md

This breaks up the CSS section into using and modifying the design system CSS.

Reorder sections on the for developers page

---

src/_documentation/for-developers.md

Define the component pieces (no pun intended) of the design system.

Add parts of the design system

---

src/_content-style-guide/writing-for-seo.md
src/_documentation/whats-new.md

@jenniferlee-dsva I added our most recent updates for the what's new section.

adding new what's new entry

---

src/_documentation/for-developers.md

Link to the full contributing documentation from our developers page.

Link to contributing doc

---

src/search.json

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/25447
The title says it all.
How it works: https://github.com/christian-fei/Simple-Jekyll-Search#create-searchjson

Add search for experimental design section

---

src/_experimental-design/contributing-code.md

Documentation for contributing code for experimental designs.

Code contributions to experimental designs

---

src/_documentation/contributing-to-the-design-system.md

adding guidance about uploading assets

adding guidance about uploading assets

---

src/_design/icons.md

Closes <https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/221>
Documentation has also been added to Storybook (with updates to some components) - https://github.com/department-of-veterans-affairs/component-library/pull/166

Update icon accessibility documentation

---

src/_content-style-guide/bulleted-lists.md

Adding an item about what to do for punctuation if a bulleted item contains a fragment and additional sentence

Updating bulleted list entry for fragments and punctuation

---

src/_content-style-guide/00_word-list.md

@DanielleThierryUSDSVA @bethpottsVADEPO I took out the "awkward style" part of this entry and reworded the rest of the sentence a bit. Let me know what you think.

updating Veteran entry

---

src/_content-style-guide/dates-and-numbers.md

@DanielleThierryUSDSVA @bethpottsVADEPO I've added the info about the extra four digits in a zip code to our address section. Let me know what you think.

Adding info about zip codes

---

src/_components/additional-info.md

Now that `<va-additional-info>` is published, we want to update the docs following https://github.com/department-of-veterans-affairs/component-library/pull/221#discussion_r762354016

Use story for updated additional info web component

---

src/_components/accordions.md

Related PR: https://github.com/department-of-veterans-affairs/component-library/pull/255

34126 Accordion Documentation Fix Storybook

---

src/_documentation/for-developers.md

Related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/35528

Update React binding import path

---

src/_components/tabs.md

@GnatalieH let me know what you think of my changes.

Copyedit of tabs document

---

src/_components/pagination.md

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/35101
Updated Pagination Storybook link to point to `va-pagination` web component

Update Pagination Storybook link

---

src/_design/html/links.html

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/639
Remove bold font weight on link

639 Links Preview Remove Bold Font Weight

---

src/_components/telephone.md

Ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/36554

36554 VA Telephone Documentation

---

src/_components/html/links.html
src/_components/links.md

I know this solution is not ideal as it creates another file to maintain, but I was unable to get it working otherwise.
Things I tried:
- Creating a new variable named contentGlobal and using `{% include {{ include.contentGlobal }} %}`
- Creating a new variable, capturing the value and passing it directly instead of using `include`
I kept running into `Invalid syntax for include tag. File contains invalid characters or sequences` build errors.

Add relative links html

---

src/_includes/color-example.html

https://user-images.githubusercontent.com/36863582/157991035-e73fef69-44da-41f7-bdbb-090f1481f487.mov

Add click to copy button for Colors

---

src/_components/banners.md
src/_components/promo-banners.md
src/_documentation/whats-new.md

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/35159
This also improves the documentation I originally provided as part of: https://github.com/department-of-veterans-affairs/va.gov-team/issues/35106 - since I did not flesh out the usage portions when that ticket was originally completed as I should have done

35159 promo banner web component docs

---

src/_components/tables.md

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/35148
This updates the storybook stories to point to the web component version.

Update table component documentation

---

src/_documentation/whats-new.md

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/35148
Following this pattern:
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/696f27c94e3afed2ffc294a241c5588ab5cc34ba/src/_documentation/whats-new.md?plain=1#L33-L38

Add table section to whats-new

---

package-lock.json
package.json

https://github.com/department-of-veterans-affairs/va.gov-team/issues/39750
Errors no longer show on build

Bump Formation v7.0.1

---

src/_components/accordions.md
src/_includes/component-docs.html

Add props and events docs

---

src/_components/alert.md
src/_includes/storybook-preview.html

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39872
https://github.com/department-of-veterans-affairs/component-library/pull/370

39872 Alert Documentation Update

---

src/_components/form-controls.md

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/39962

Add example and update storybook link for Checkboxes

---

package-lock.json
src/_components/pagination.md

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39969
https://github.com/department-of-veterans-affairs/component-library/pull/379

39969 Pagination view in SB

---

src/_components/accordion.md

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39860
https://github.com/department-of-veterans-affairs/component-library/pull/383

39860 Accordions Documentation

---

src/_components/form-controls.md

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/39957

Update preview link text for Select Box

---

src/_components/form-controls.md

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/39929

Add success example and update link text for Text Input

---

package-lock.json
package.json
src/_data/component-docs.json

Bump component library to fix issue with `<a>` in JSDoc inside of promo banner component

Bump Component Library 8.6.1

---

src/index.html

Fixing a few links on the homepage.

fix links on homepage

---

src/_about/for-designers.md
src/_components/sidenav.md
src/_data/component-docs.json
src/_foundation/layout/flexbox-grid.md
src/_foundation/layout/html/2-col-content-left-iframe.html
src/_foundation/layout/html/2-col-content-right-iframe.html
src/_foundation/layout/html/flexbox-grid-responsive-iframe.html
src/_foundation/layout/page-layouts.md
src/_patterns/templates/index.md

Fixes broken links for the Foundation/Layout section and changes iFrames to partials in the Foundation/Layout section.

Fix layout links

---

src/_components/form/index.md
src/_foundation/layout/index.md
src/_foundation/utilities/index.md
src/_patterns/templates/index.md

There are a few permalinks that end with a slash and point to broken links in `In This Section`.

Fix permalinks

---

src/_components/form/index.md
src/_foundation/layout/index.md
src/_foundation/utilities/index.md
src/_patterns/templates/index.md

Reverts department-of-veterans-affairs/vets-design-system-documentation#750

Revert "Fix permalinks"

---

package-lock.json
package.json

Bump Component Library to latest release for fixes on Number Input docs

Bump Component Library to 8.6.2

---

src/_components/form/checkbox.md
src/_components/form/number-input.md
src/_components/form/radio-button.md
src/_components/form/select.md
src/_components/form/text-inputs.md

https://github.com/department-of-veterans-affairs/component-library/pull/396
Add in missing events and props table for Form Controls input pages

Event and Prop Information for Form Control Inputs

---

src/_about/for-designers.md
src/_about/for-developers.md

Fixing a link on the For Designers page and a few links on the for developers pages.

Fix links on for designers and for developers pages

---

.github/workflows/issue-automation.yml

There's a permission error with the first query, so I'm seeing if the mutation will work if it gets the ID from a secret.

Get PROJECT_ID from secrets

---

.github/workflows/issue-automation.yml

I'm still getting errors which seem to be about permissions, so I'm seeing if the PAT will actually work

Use PAT instead of GITHUB_TOKEN

---

src/_components/back-to-top.md

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/40110

Update Storybook preview link text for va-back-to-top

---

src/_about/whats-new.md

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39734

Number Input component announcement

---

src/_components/process-list.md

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/40111

Update documentation for va-process-list

---

src/_components/progress-bar.md

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/40112

Update Storybook preview link text for Progress bars

---

src/_patterns/forms/index.md

This will add an anchor link to the html document.

Use a link on the form patterns page

---

src/_components/alert.md

Breaks the page up a bit more with additional h2s to call out the variations.

Adds dismissible and heading variations to Alert. 

---

.github/ISSUE_TEMPLATE/component_accessibility_review.md
.github/ISSUE_TEMPLATE/component_announcement.md
.github/ISSUE_TEMPLATE/component_design.md
.github/ISSUE_TEMPLATE/component_development.md
.github/ISSUE_TEMPLATE/component_documentation.md
.github/ISSUE_TEMPLATE/component_final_review.md
.github/ISSUE_TEMPLATE/component_pattern_audit.md
.github/ISSUE_TEMPLATE/component_sketch.md

Of course I forgot to put quotes around the title. 🤦‍♀️

fix issue template frontmatter

---

src/_components/search-input.md

Add typeahead example to Search input

---

.github/ISSUE_TEMPLATE/component_design.md
.github/ISSUE_TEMPLATE/component_development.md

Adding tasks to the component design and development issue templates to check for existing issues in the backlog.

add tasks to check for outstanding issues

---

package-lock.json
package.json
src/_components/search-input.md

This PR updates `component-library` to version 10.0.0 to include the latest `component-docs.json` used to generate code usage.

Update code usage for va-search-input

---

src/_about/whats-new.md

Add search input to What's New

---

src/_components/featured-content.md

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/40188

Update documentation for va-featured-content

---

src/_about/whats-new.md
src/_components/form/checkbox.md
src/_components/form/number-input.md
src/_components/form/select.md
src/_components/form/text-input.md
src/_components/form/textarea.md

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/38913
https://github.com/department-of-veterans-affairs/component-library/pull/436

38913 Native Events Documentation

---

src/_foundation/icons.md
src/_foundation/index.md

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/37062

37062 Design Accessibility Docs

---

src/_components/form/date-text-input.md
src/_components/form/index.md

Closes part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/845
https://github.com/department-of-veterans-affairs/component-library/pull/438

845 Date Text Input Documentation

---

src/_components/form/textarea.md

Part of #872 
This is to address @humancompanion-usds 's [feedback](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/872#issuecomment-1147755165) on the ticket.

Update textarea component docs

---

src/_about/for-developers.md

Closes: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/868

868 Web Component Intro and Migration Information

---

src/_about/for-developers.md

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/900

Add native event documentation

---

package-lock.json
package.json

This gives us the latest `component-docs.json` used in generating our web component code usage.

Update component-library dependency

---

src/assets/javascripts/vendor/search.js
src/assets/stylesheets/_components/_search-results.scss
src/results.html
src/search.json

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/776

Add description to search results

---

src/_components/breadcrumbs.md

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/40186

Add sketch-link for Breadcrumbs

---

.github/workflows/deploy.yml

Change the build order so that the component-library JS scripts get built & included in CI.

Change build order for deploy

---

.github/workflows/deploy.yml

Reverts department-of-veterans-affairs/vets-design-system-documentation#1008

Revert "Change build order for deploy"

---

src/_about/whats-new.md

Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/820

Add va-button to whats new

---

src/_components/alert-expandable.md

Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1011

Update documentation for alert-expandable

---

src/_content-style-guide/error-messages/index.md
src/assets/stylesheets/_layout/_site-content.scss

Adding a min-width fixes the issue though I still don't understand what's causing it for just this new sub-set of pages.
(Also fixes a broken link.)

Fixes mysteriously disappearing sidenav. [Fixes #1042]

---

.github/ISSUE_TEMPLATE/_DST-basic_issue_template.md
.github/ISSUE_TEMPLATE/_DST-component_accessibility_review.md
.github/ISSUE_TEMPLATE/_DST-component_announcement.md
.github/ISSUE_TEMPLATE/_DST-component_design.md
.github/ISSUE_TEMPLATE/_DST-component_development.md
.github/ISSUE_TEMPLATE/_DST-component_documentation.md
.github/ISSUE_TEMPLATE/_DST-component_final_review.md
.github/ISSUE_TEMPLATE/_DST-component_pattern_audit.md
.github/ISSUE_TEMPLATE/bug_template.md
.github/ISSUE_TEMPLATE/documentation_request_form.yml
.github/ISSUE_TEMPLATE/experimental_design_request.md
.github/ISSUE_TEMPLATE/support_question.md

And of course I forgot to update the template names when I updated the file names 🙄

update template names

---

.github/ISSUE_TEMPLATE/_DST-basic_issue_template.md
.github/ISSUE_TEMPLATE/_DST-component_accessibility_review.md
.github/ISSUE_TEMPLATE/_DST-component_announcement.md
.github/ISSUE_TEMPLATE/_DST-component_design.md
.github/ISSUE_TEMPLATE/_DST-component_development.md
.github/ISSUE_TEMPLATE/_DST-component_documentation.md
.github/ISSUE_TEMPLATE/_DST-component_final_review.md
.github/ISSUE_TEMPLATE/_DST-component_pattern_audit.md
.github/ISSUE_TEMPLATE/bug_template.md
.github/ISSUE_TEMPLATE/documentation_request_form.yml
.github/ISSUE_TEMPLATE/experimental_design_request.md
.github/ISSUE_TEMPLATE/support_question.md

Let's try numbers this time and see if that works better for re-ordering the templates.

trying to reorder the templates again

---

src/_patterns/forms/sub-task.md
src/_patterns/wizards.md

Attempts to address the issues that reviewers raised and adds a11y guidance from DK and Josh.

Revises sub-task and adds DK's doc to the Wizard pattern. [Fixes #1051]

---

src/_content-style-guide/numbers.md

Fix "scientific" typo in Content style guide

---

src/_content-style-guide/00_word-list.md

Deleted duplicate entry of "suicide"

Removing duplicate entries in word list

---

src/_components/banner/index.md

The "Closeable" story was renamed to "Dismissible" in https://github.com/department-of-veterans-affairs/component-library/pull/520 and now this page needs to be updated.

Update banner story link

---

_config.yml

Updates the links to our issue templates

update links to issue templates

---

src/_about/designers/design-libraries.md
src/_about/designers/index.md
src/_about/designers/sketch-for-teams-at-va.md
src/_about/for-developers.md

Fixes up intro text and adds consistency for both design and dev sections.

Fixes links for designers section. 

---

src/index.html

Just a quick example of updating the homepage.

Example update to homepage

---

package-lock.json
package.json

Verified compiles locally:
And also displaying updated prop name from v13.10.3:

Update component library to v13.10.3

---

package-lock.json
package.json

Change log details: https://github.com/department-of-veterans-affairs/component-library/releases/tag/v13.11.1
Verified working locally:

Update component library to v13.11.1

---

package-lock.json
package.json

This PR will update the design system component library to the latest release. Verified running locally.
https://github.com/department-of-veterans-affairs/component-library/releases/tag/v15.0.0

Update component library to v15.0.0

---

package-lock.json
package.json
src/_components/accordion.md

Update component library to v16.1.0

---

src/_components/card.md
src/_components/html/card-benefit-application-drafts.html
src/_components/html/card-benefit-payments.html
src/_components/html/card.html

Part one of Card guidance updates.

Adds va-card and cleans up the guidance page on Cards. [Amends #1419]

---

src/_about/contributing/add-a-component-or-pattern-once-approved.html
src/_about/developers/contributing.md

Updates to the contributing page of the developers' section of the docs website to reflect how to upload actual code, rather than an experimental design.
Closes #1717.

Updates to contributing documentation

---

package-lock.json
package.json

- Upgrade formation version to ^7.0.8 in package.json
- Fixes a bug where buttons would sometimes overflow from their containers on mobile
- Github Issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1798
- Related fix in veteran-facing-service-tools: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/936
- Manual testing
Before:
After:
- This seems to have mostly affected buttons when they are in the shadow DOM of web-components and viewed on mobile, however this could have affected other buttons in a narrow container.

1798 - Upgrade formation version 

---

src/_about/developers/using-web-components.md

Adding instructions for how to use web components in "V3 Mode".
Closes #1784

Adding V3 web component usage instructions - 1784

---

src/_about/whats-new.md
src/_components/alert.md
src/_components/banner/maintenance.md
src/_components/table.md
src/_includes/_banner-whats-new.html

The other changes were in MVP components and thus don't need to be added yet.

Adds banner maintenance and table variations. [Fixes #1856]

---

src/_about/developers/implementing-design-work.md

Fixed broken naming conventions link on implementing-design-work.md

---

package-lock.json
package.json

Release notes: https://github.com/department-of-veterans-affairs/component-library/releases/tag/v18.0.0
Verified locally:

Update component library to v18.0.0

---

package-lock.json
package.json

Updating to the latest release but I'm also checking if this resolves [the issue we have](https://dsva.slack.com/archives/C01DBGX4P45/p1691004843859989) with the `va-accordion` component not loading on the [forms label list](https://design.va.gov/content-style-guide/form-labels#form-label-masterlist).
Previewed locally:

Update component library to latest release v18.0.1

---

_config.yml
src/_about/designers/design-libraries.md
src/_about/designers/sketch-for-teams-at-va.md
src/_components/accordion.md
src/_components/additional-info.md
src/_components/alert.md
src/_components/breadcrumbs.md
src/_components/button/button-pair.md
src/_components/button/index.md
src/_components/form/checkbox.md
src/_components/form/memorable-date.md
src/_components/form/number-input.md
src/_components/form/progress-bar-segmented.md
src/_components/form/radio-button.md
src/_components/form/select.md
src/_components/form/text-input.md
src/_components/form/textarea.md
src/_components/index.md
src/_components/modal.md
src/_components/privacy-agreement.md
src/_components/process-list.md
src/_includes/_banner-whats-new.html
src/_includes/_component-uswds.html
src/_layouts/component.html
src/assets/img/uswds-logo.svg
src/assets/stylesheets/_components/_badge.scss
src/assets/stylesheets/application.scss

Updates documentation on USWDS v3 upgrade.

Add sketch libraries 1784

---

package-lock.json
package.json

Release notes: https://github.com/department-of-veterans-affairs/component-library/releases/tag/v19.1.0

Update component-library package.json version to latest release

---

src/_components/accordion.md
src/_components/alert.md
src/_components/form/select.md
src/_components/pagination.md
src/_components/privacy-agreement.md
src/_components/process-list.md
src/_components/sidenav.md
src/_data/component-checklist/va-accordion.yml
src/_data/component-checklist/va-pagination.yml
src/_data/component-checklist/va-process-list.yml
src/_data/component-checklist/va-select.yml
src/_includes/a11y/alerts.md

Adds the pointers to v3 guidance for 5 additional components. Also adds a component checklist for a few of these components.

Guidance v3 1753

---

package.json
yarn.lock

Bumps version number of component library to 21.0.1

DS version bump to 21.0.1

---

package.json
yarn.lock

Component library version bump to v22.0.0

v22.0.0 update

---

package.json
yarn.lock

Bumps component library to 23.0.0

bump component library version

---

README.md

Adding this note will provide BrowserStack accounts for approved open source projects.

Add browserstack note

---

package.json
yarn.lock

Updates component library to latest release

update component library to 31.0.1

---

package.json
yarn.lock

Updates component library to latest release

update component library to 32.1.0

---

src/_data/tokens/vads-color-component.csv
src/_data/tokens/vads-color-semantic.csv
src/_data/tokens/vads-spacing-semantic.csv
src/_foundation/color-palette.html
src/_foundation/spacing-units.md
src/_includes/spacing-tokens.html

Also adds component colors and fixes rgba colors to display correctly.

Adds semantic spacing tokens. [Amends #2296]

---

src/_content-style-guide/00_word-list.md

Adding the following entries to the word list:
-condition vs. disability
-intent to file form
-mobile phone 
-smartphone
@bethpotts I made these additions that you and @DanielleThierryUSDSVA already approved. Could you merge these when you get a chance? Thank you!

New entries to word list

---

package.json
src/_components/summary-box.md
yarn.lock

Update featured content to summary box and bump `component-library` to 37.0.0

Update to summary box, bump to 37.0.0

---

src/_data/content/patterns/ask-users-for/addresses.csv
src/_patterns/ask-users-for/addresses.md

error messages, and hint text from content database.,

Updates labels

---

src/_components/link/index.md

fixing broken link on links page under Accessibility

Link fix.md

---

src/_components/breadcrumbs.md
src/_foundation/logos.md

Also, updates breadcrumb guidance which should fix issue #74133

Updates breadcrumb to show mobile view. Adds link to logos. These were both mentioned in a recent audit.

---

src/_components/additional-info.md
src/_components/button/index.md
src/_components/experimental-design-template.md

Minor updates to places that reference WCAG 2.1

WCAG 2.2 updates

---

src/_includes/content/conditionally-revealed-fields.md

Fixed a typo, and some other grammar issues.

Fixed typo

---

src/_content-style-guide/00_word-list.md

per [this slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1712076604005559?thread_ts=1712002651.162639&cid=C04KW0B46N5)

Adding "contention" to content style guide word list

---

src/_components/alert-expandable.md

@humancompanion-usds I took a crack at adding the success variation and minor guidance. Feel free to edit or provide comments.

Adds success variation. [Fixes #2690]

---

.github/workflows/deploy.yml

Changing out npm install and build with yarn install and yarn run build

Updating deploy to use yarn

---

src/_patterns/ask-users-for/multiple-responses.md

Clarify single-page L&L guidance use

---

package.json
yarn.lock

Updates component library to 42.2.1

update component library to 42.2.1

---

package.json
yarn.lock

update "@department-of-veterans-affairs/component-library" to "^44.0.0",

update component-library to 44.0.0

---

package.json
yarn.lock

Updates to latest version of component library and css-library

update component library and css-library

---

package.json
yarn.lock

bump comp lib version

---

src/_components/summary-box.md

#2955 Added a h2 as an option for the heading levels

#2955 Update summary-box.md with option to use a H2 heading level

---

src/_includes/content/phone-numbers.md

@laurwill I tried to make minor adjustments to your phone number aria PR and it made me open up a new branch. Are you able to merge? 
Otherwise, your PR looks great! Thank you so much for adding it.

Aria guidance adjustment

---

package.json
yarn.lock

Updating comp-lib and css-lib.

Component-lIbrary and css-library update

---

src/_components/link/index.md

Increase example iframe sizes

---

package.json
yarn.lock

Updates component-library and css-library dependencies

update comp-lib and css-lib versions

---

package.json
src/_data/margins.yml
yarn.lock

Updates the package versions for css-library and the margin docs with correct values for x, left, and right.

update package versions and margin docs

---

src/_about/accessibility/index.md

Fix the a11y testing link that was accidentally updated to point to something on GitHub.

Fix a11y testing link

---

src/_includes/components/label-errors.html

Fix typo in error handling docs

---

package.json
yarn.lock

Updating comp-lib to latest version.

Updating comp-lib to latest v48.3.0

---

src/_data/component-checklist/a11y/README.md
src/_data/component-checklist/a11y/a11y-audit.csv
src/_data/component-checklist/va-alert-sign-in.yml

This component went through staging review. No issues were reported on the component itself with regard to accessibility.

Add audit data for alert sign in

---

src/_content-style-guide/neutral-and-inclusive-language.md
src/_content-style-guide/they-their.md

More content tweaks to language on several pages of content style guide

Mor fixes to style guide

---

src/_includes/content/links-vs-buttons.md

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3579
Updated links vs. button section with a bullet point for download links.

Update link/button guidance for downloads

---

package.json
yarn.lock

Update component library to v49.0.0

---

src/_data/tokens/vads-color-semantic.csv

Color Palette: Add mobile foreground tokens

---

src/_patterns/ask-users-for/files.md

Fix the embed to storybook's file input error story.

Update embed to va-file-input error in files.md

---

src/_components/service-list-item.md

Description:
- Replaces the links to images for the examples to instead use the actual storybook embeds.
- Removes sections that don't have content

add storybook embed, remove unused sections

---

package.json
yarn.lock

Updates component library to 49.4.1 and css-library to 0.20.0

Update package versions

---

src/_components/form/radio-button.md

Add accessibility consideration for radio button legend

---

src/_components/language-toggle.md

Closes #3952 
[Open Preview Environment](https://dev-design.va.gov/3962)

va-language-toggle: Adds two language variation

---

src/_includes/header.html

Prod has broken images in the gov banner so this should fix it:
[Open Preview Environment](https://dev-design.va.gov/3963)

Fix gov banner image paths

---

package.json
src/assets/stylesheets/_layout/_content-wrappers.scss
yarn.lock

Removed square bullet styles to align with VA list styles.
https://dev-design.va.gov/3972/about/whats-new

Remove custom list styles and update CSS-Library to latest 

---

src/_includes/content/select-options.md

Closes #3959 
This guidance is in one file that is relevant to and included on the following component pages:
* Combo box
* Radio button
* Select
* Search input
[Open Preview Environment](https://dev-design.va.gov/3974)

Multiple Form Components: Updates guidance on selecting components by option count.

---

src/_components/form/combo-box.md

Closes #3956 
[Open Preview Environment](https://dev-design.va.gov/3957)

Combo Box: Updates content from review

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/deploy-reusable.yml
.github/workflows/preview.yml

This will update the PR description content automatically with a link to the preview environment so that it doesn't have to be done manually. It uses the [update-pr-description action](https://github.com/marketplace/actions/update-pr-description).
[Open Preview Environment](https://dev-design.va.gov/3976)

Add Github action to update PR description with preview link

---

src/_templates/forms/form-step-minimal.md

Added more links for examples and dev code
#3979  
[Open Preview Environment](https://dev-design.va.gov/3983)

Form step - Minimal: Add examples and dev link

---

src/_components/link/index.md
src/_components/template.md

Small tweaks to the component template to incorporate mobile app.
Closes #2391 
This will be updated automatically 🪄✨

Update component template for mobile. [Fixes #2391]

---

src/_templates/forms/form-step-minimal.md

Added usage guidance to the "form step - minimal template page"
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/2131
[Open Preview Environment](https://dev-design.va.gov/3996)

Form step - Minimal Add usage guidance

---

src/_components/language-toggle.md
src/_data/component-checklist/va-language-toggle.yml

Closes #3991 
[Open Preview Environment](https://dev-design.va.gov/4014)

Language Toggle: Add component checklist

---

src/_components/link/action.md
src/_components/link/index.md

Adds guidance for the new Primary entry variation. Cleans up some oddities in the the Link - Action and Link guidance.
Closes #[4031]
[Open Preview Environment](https://dev-design.va.gov/4032)

 Link - Action: Adds the new Primary entry variation. [Fixes #4031]

---

package.json
yarn.lock

Updating the component-library package to the latest release:
- https://github.com/department-of-veterans-affairs/component-library/releases/tag/v50.2.1
[Open Preview Environment](https://dev-design.va.gov/4036)

Update component-library package - v50.2.1

---

src/_components/form/radio-button.md

Closes #3837 
[Open Preview Environment](https://dev-design.va.gov/4073)

Radio Button: Add mobile examples

---

src/_components/table.md

I noticed there are still some references to the original v1 table component. This PR will clean up things related to that.
related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3326
[Open Preview Environment](https://dev-design.va.gov/4077)

va-table: remove old references to deprecated v1 version

---

src/_components/form/radio-button.md
src/_components/text.md

Text: Adds Text as new component to guidance, specific to the mobile application.
Closes #[3839](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3839)
[Open Preview Environment](https://dev-design.va.gov/4082)

Text: Adds text as new component to guidance. [Fixes #3839]

---

src/_patterns/help-users-to/update-prefilled-information.md

Help users to update prefilled information: Adds missing related components to pattern.
Closes #[4042](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4042)
[Open Preview Environment](https://dev-design.va.gov/4100)

Help users to update prefilled information: Adds missing related components to pattern. [Fixes #4042]

---

src/_components/search-filter.md
src/_data/component-checklist/va-search-filter.yml
src/_templates/search-results.md

_Provide a brief summary of what this PR does, if the title doesn't fully explain it._
[Open Preview Environment](https://dev-design.va.gov/4099)

Adds guidance for search filter.

---

package.json
yarn.lock

_Provide a brief summary of what this PR does, if the title doesn't fully explain it._
[Open Preview Environment](https://dev-design.va.gov/4127)

Update component-library to release v50.2.2

---

.github/ISSUE_TEMPLATE/1_bug_template.md
.github/ISSUE_TEMPLATE/3_experimental_design_request.md
.github/ISSUE_TEMPLATE/4_support_question.md
.github/ISSUE_TEMPLATE/DSF-kickoff-tasks.md
.github/ISSUE_TEMPLATE/DSF-research.md
.github/ISSUE_TEMPLATE/DST-basic_issue_template.md
.github/ISSUE_TEMPLATE/DST-component_accessibility_review.md
.github/ISSUE_TEMPLATE/DST-component_design.md
.github/ISSUE_TEMPLATE/DST-component_development.md
.github/ISSUE_TEMPLATE/DST-component_documentation.md
.github/ISSUE_TEMPLATE/DST-component_final_review.md
.github/ISSUE_TEMPLATE/DST-component_pattern_audit.md
.github/ISSUE_TEMPLATE/DST_component_design_2.md
.github/ISSUE_TEMPLATE/onboarding--enter-name-.md

[Open Preview Environment](https://dev-design.va.gov/4138)

Added a new onboarding template

---

src/_components/form/file-input.md

- Replaced images  for single file uploaded and multiple file uploaded with storybook examples
- Multiple files uploaded example
- Single file upload example
- Removes some duplicate examples for multiple files
Closes #3002 
[Open Preview Environment](https://dev-design.va.gov/4152)

File input: Added storybook examples for file input

---

src/_components/snackbar.md
src/_components/text.md

Snackbar: Adds component 
Closes #[4132](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4132)
[Open Preview Environment](https://dev-design.va.gov/4145)

Snackbar: Adds component [Fixes #4132]

---

config/gulp/json.js
package.json
src/_data/component-maturity-figma.json

This generates, hopefully, a JSON file Figma can consume to show maturity level thereby syncing our maturity levels across documentation.
Closes #[3905](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3905)
[Open Preview Environment](https://dev-design.va.gov/4155)

Adds a gulp task for generating Figma output. [Fixes #3905]

---

src/_data/component-maturity.json
src/_patterns/ask-users-for/social-security-number.md

Addresses some of the shortcomings in the guidance of the pattern.
Amends #[#3865]
[Open Preview Environment](https://dev-design.va.gov/4243)

Ask users for SSN: Updates pattern to include guidance on when and when not to ask or allow SSN to be changed

---

src/_components/form/telephone-input.md

Updates content guidance from staging review
Closes #4266
Closes #4260 
Closes #4265 
[Open Preview Environment](https://dev-design.va.gov/4286)

109677 telephone staging review

---

package.json
yarn.lock

This PR updates component-library to 50.5.0, the latest version
[Open Preview Environment](https://dev-design.va.gov/4314)

Update component-library to 50.5.0

---

src/_components/form/telephone-input.md

Update figma link for telephone component
N/A
[Open Preview Environment](https://dev-design.va.gov/4317)

Update figma link for telephone component

---

src/_about/developers/implementing-design-work.md
src/_data/component-maturity.json

Revises the expectations for developers.
Closes #[#4319 ]
[Open Preview Environment](https://dev-design.va.gov/4322)

Revises the expectations for developers. [Fixes #4319]

---

src/_about/developers/install.md

With the deprecate of Formation, we needed to add new install instructions for the CSS-Library.
https://dev-design.va.gov/4432/about/developers/install
The integration examples link isn't working because the PR isn't merged yet.
- https://github.com/department-of-veterans-affairs/component-library/pull/1592
closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3663
[Open Preview Environment](https://dev-design.va.gov/4432)

Update install instructions for CSS-Library

---

src/_components/button/button-segmented.md

[Open Preview Environment](https://dev-design.va.gov/4463)

Segmented Button: Fix story links

---

.github/ISSUE_TEMPLATE/DST-add-icon.md

Adding instructions on how to add an icon.
There are 6 different PR's you have to complete to add icons. This issue template creates instructions on how to do that.
No issue related to this.
[Open Preview Environment](https://dev-design.va.gov/4470)

Issue template: Create DST-add-icon.md issue template

---

src/_components/link/index.md

Adding new PII/PHI guidance to the link component
[Open Preview Environment](https://dev-design.va.gov/4474)

Update index.md: Adding PII/PHI guidance

---

src/_about/developers/install.md

Fixes a broken link on the developers/install page.
I didn't file an issue for this.
[Open Preview Environment](https://dev-design.va.gov/4492)

Fixes a broken link to the Vite guidance Jami wrote.

---

src/_about/developers/using-web-components.md

I noticed these USWDS v3 migration guidelines still in the [developer docs](https://design.va.gov/about/developers/using-web-components#uswds-v1-to-v3-migration). Since this process has been complete, I think we can remove it.
no related issue
[Open Preview Environment](https://dev-design.va.gov/4525)

Remove USWDS v1 to v3 migration guidelines

---

src/_patterns/help-users-to/update-prefilled-information.md

Figma link was pointing to incorrect figma files
N/A
[Open Preview Environment](https://dev-design.va.gov/4539)

Update link to figma

---

src/_about/developers/install.md

_Provide a brief summary of what this PR does, if the title doesn't fully explain it._
[Open Preview Environment](https://dev-design.va.gov/4555)

Fix broken link to font-face import example on install instructions

---

package.json
yarn.lock

This PR updates component library to 52.0.0
[Open Preview Environment](https://dev-design.va.gov/4672)

update to latest component library release

---

src/_content-style-guide/title-tags.md

Fixing the spacing in the PII/PHI like this/not this example
[Open Preview Environment](https://dev-design.va.gov/4655)

Update title-tags.md: Fixing spacing in the PII/PHI example

---

json_data_cache/component_library_releases.json
json_data_cache/site_releases.json

Updated What's new page for Sprint 9
[Open Preview Environment](https://dev-design.va.gov/4693)

What’s New: Update release notes

---

src/_components/alert/alert-expandable.md
src/_components/alert/index.md
src/_components/button/button-segmented.md
src/_components/button/index.md
src/_components/form/autosave.md
src/_components/form/label.md
src/_components/link/index.md
src/_foundation/layout/flexbox-grid.md
src/_patterns/ask-users-for/feedback.md
src/_patterns/help-users-to/check-eligibility.md
src/_patterns/help-users-to/complete-a-sub-task.md
src/_templates/forms/confirmation.md
src/_templates/forms/review.md

@allison0034 let me know in a conversation there were a few dead links in VADS. I ran a scanning tool and found the following 404s from links in VADS. This PR updates those. (There are likely a few more 404s as the scan could only crawl the first 2000 links (and servers started bouncing the bot))  But fixing some is better than none.
| Bad URL …

Fixes a bunch of dead links in VADS

---

src/_components/tabs.md

Updates tab guidance to fix issues found in staging review. 
Closes:
- DST Staging Review (Consider): Add link to Search Results template in "When to consider something else" [#4677](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4677)
- DST Staging Review: Confusing language in component description  [#4681](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4681)
- DST Staging Review: Passive voice in tab overflow description  [#4682](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4682) 
- DST Staging Review: Include guidance about headings inside of tab content [#4678](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4678) …

Tabs: Updated guidance based on staging review findings

---

src/_templates/forms/form-step.md

Clarifying heading levels within a form flow
N/A
[Open Preview Environment](https://dev-design.va.gov/4730)

Clarifying form page headings

---

.github/ISSUE_TEMPLATE/1_bug_template.md

Adds URL to bug template
N/A
[Open Preview Environment](https://dev-design.va.gov/4739)

Adds URL to bug template

---

src/_components/form/file-input.md

These guidelines are based on the multiple file input slot guidelines discussion the team had yesterday which I have [summarized here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4804#issuecomment-3324330421). If I have not captured this accurately though, don't hesitate to give feedback.
I also wasn't certain about the location of the guidelines because we also have general file upload pattern page so if we feel like it needs to be in a different location, I'm happy to move it.
https://dev-design.va.gov/4861/components/form/file-input#additional-guidance-for-va
closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4804
[Open Preview Environment](https://dev-design.va.gov/4861)

va-file-input-multiple:add slotted content consideration guideline

---

.github/ISSUE_TEMPLATE/DST-add-icon.md
src/_components/icon.md

- Expanded documentation to clarify when to request a new icon for the Design System and when not to. 
- Updated submission instructions and provided additional context for experimental requests.
- Fixed broken link at the bottom of the page
Closes #4620 
[Open Preview Environment](https://dev-design.va.gov/4873)

Icons: Add guidelines for requesting new icons

---

package.json
yarn.lock

Component Library release notes:
https://github.com/department-of-veterans-affairs/component-library/releases/tag/v53.1.0
[Open Preview Environment](https://dev-design.va.gov/4902)

Update component-library to latest v53.1.0
